### ISSUE TITLE
hdf2ckl error "delete this.baseFlags?.json"

### ISSUE THREAD

**Issue by usteve94** [mitre/saf#1853]
I ran my inspec and generated a .json file for my esxi, vm, vcsa environment.

when I run the following:
saf convert hdf2ckl -i ./vcsa.json -o ./VCSAReport.ckl --hostname <IP Address> --fqdn <fqdn name>

I just downloaded the saf-v1.2.30-amd64.deb pkg.
Running Pwsh v 7.3.7
Running PowerCLI v 13.1.0

This is returned
/usr/local/lib/node_modules/@mitre/saf/node_modules/@oclif/core/lib/command.js:45
            delete this.baseFlags?.json;
                                  ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/@mitre/saf/node_modules/@oclif/core/lib/index.js:5:19)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)

**Comment by aaronlippold** [comment]
Yours,

--------------------

Aaron Lippold

Chief Architect – MITRE Security Automation Framework (SAF)

https://saf.mitre.org<https://saf.mitre.org/>

Principal Cyber Security Engineer



571-384-9233

***@***.******@***.***>



https://info.mitre.org/orgs/L521

<https://aka.ms/o0ukef>
________________________________
From: usteve94 ***@***.***>
Sent: Monday, October 2, 2023 11:46:03 AM
To: mitre/saf ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [EXT] [mitre/saf] hdf2ckl error "delete this.baseFlags?.json" (Issue #1853)

I ran my inspec and generated a .json file for my esxi, vm, vcsa environment. when I run the following: saf convert hdf2ckl -i ./vcsa. json -o ./VCSAReport. ckl --hostname --fqdn I just downloaded the saf-v1. 2. 30-amd64. deb pkg. Running Pwsh v


I ran my inspec and generated a .json file for my esxi, vm, vcsa environment.

when I run the following:
saf convert hdf2ckl -i ./vcsa.json -o ./VCSAReport.ckl --hostname --fqdn

I just downloaded the saf-v1.2.30-amd64.deb pkg.
Running Pwsh v 7.3.7
Running PowerCLI v 13.1.0

This is returned
***@***.******@***.***/core/lib/command.js:45
delete this.baseFlags?.json;
^

SyntaxError: Unexpected token '.'
at wrapSafe (internal/modules/cjs/loader.js:915:16)
at Module._compile (internal/modules/cjs/loader.js:963:27)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
at Module.load (internal/modules/cjs/loader.js:863:32)
at Function.Module._load (internal/modules/cjs/loader.js:708:14)
at Module.require (internal/modules/cjs/loader.js:887:19)
at require (internal/modules/cjs/helpers.js:74:18)
at Object. ***@***.******@***.***/core/lib/index.js:5:19)
at Module._compile (internal/modules/cjs/loader.js:999:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)

**Comment by Amndeep7** [comment]
Hi @usteve94, I believe the issue might be that you need to provide values for the hostname and fqdn flags.  

If that doesn't resolve the issue, it would help if you could share your (possibly anonymized) inspec results file here or feel free to send it to me at amann@mitre.org so that we can debug your issue.
