### ISSUE TITLE
Cannot find module '@oclif/core'

### ISSUE THREAD

**Issue by kb7791** [mitre/saf#2892]
afetr npm installing saf and trying to just run saf in a terminal this error is being thrown.

```
[local@localhost powercli]$ saf
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module '@oclif/core'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/@mitre/saf/bin/run:3:15)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
[local@localhost powercli]$ npm -v
6.14.11
[local@localhost powercli]$ node -v
v10.24.0
```

**Comment by Amndeep7** [comment]
Hi @kb7791.  You seem to be using a very old version of node.  Could you try using the latest on the v18.x release branch?

I'd also like to see what command you're using to install the SAF CLI via npm.

**Comment by kb7791** [comment]
I will update my node version when I get to the office.

I used ```npm install -g @mitre/saf``` to install

**Comment by kb7791** [comment]
Node update did the trick. Doesnt seem like rhel8 has the latest nodejs and you have to grab it directly from nodejs site. @Amndeep7 thank you for the help.

**Comment by Amndeep7** [comment]
Hi @kb7791 happy to see that that worked out for you. If you're cool with it, I'd love to learn more about your use case for the SAF.  Could you shoot me an email at amann@mitre.org?
